
package org.jboss.eap.example.security.web.soap.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://services.soap.web.security.example.eap.jboss.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://services.soap.web.security.example.eap.jboss.org/", className = "org.jboss.eap.example.security.web.soap.services.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://services.soap.web.security.example.eap.jboss.org/", className = "org.jboss.eap.example.security.web.soap.services.HelloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
